### ISSUE TITLE
Error: Profile with the provided email does not exist or the email is not verified

### ISSUE THREAD

**Issue by wursterje** [JetBrains/space-documents-import#1]
Importing from Confluence to Space was a challenge due to some pages being authored by users who did not exist in Space. The import process failed, showing an error message stating, "Error: Profile with the provided email does not exist or the email is not verified."

Upon reviewing the webserver logs, I noticed the following entry: "GET /api/http/team-directory/profiles/email:xxx.xxx%xxxx.de?verified=true&%24fields=%2A HTTP/1.1" 404 119 "-" "Space CLI client" "-"

To resolve the issue, I copied the pages from Confluence and changed the ownership to myself. Then, I deleted the original pages. After taking these steps, the import was successful.

**Comment by kontza** [comment]
Hi,

For future generations, this is what I tried:
1. Created a new space, with the name XFER,  in Confluence and copied everything from the main space into this XFER space.
2. I started the import which failed with the error in this issue's subject.
3. I then noticed that the Confluence admin account I was using had an email address of nobody@redacted.com.
4. I changed that to the same, verified, email address that I had on JB Space.
5. I also cloned this repo, built the app myself, and started to run the import with the newly built JAR.
6. Now the migration started.
7. Only to fail on

    ```
    Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.length()" because "csq" is null
        at com.vladsch.flexmark.util.sequence.LineAppendableImpl.append(LineAppendableImpl.java:547)
        at com.vladsch.flexmark.util.format.MarkdownWriterBase.append(MarkdownWriterBase.java:109)
        at com.vladsch.flexmark.html2md.converter.internal.HtmlConverterCoreNodeRenderer.processImg(HtmlConverterCoreNodeRenderer.java:662)
        at com.vladsch.flexmark.html2md.converter.HtmlNodeRendererHandler.render(HtmlNodeRendererHandler.java:19)
   ```
8. I tried manually exporting that NPE-inducing page, and replacing its contents with a one line of text containing "Manually exported." In the hopes that migration would manage to jump over that.
9. Did not help, even the one liner was too much.

My guess is that the entire Space is too big to this tool to import. Also, looking at the code, it really should be more fault tolerant, i.e. not to fail on a single error. Better would be to log the error, and continue on to the next document. This way, if there was a single problematic document, only that would not be imported. The current implementation forces full imports again and again in hopes of a problematic page being solved.

My suggestion to others with this problem: do as I did:
1. Export Confluence as HTML.
2. Run the exported html files through https://github.com/suntong/html2md , or similar tool, and import generated MD files into Space via folder import.
